-- Clear Light and Clear Dark for lualine, generated by clear-theme's build.py.
-- lualine picks this up for the "clear" colorscheme with its "auto" theme,
-- and reloads it when 'background' changes.
local themes = {
  light = {
    normal = {
      a = { fg = "#ffffff", bg = "#1f7bbc", gui = "bold" },
      b = { fg = "#3a4851", bg = "#edefef" },
      c = { fg = "#506573", bg = "#ffffff" },
    },
    insert = {
      a = { fg = "#ffffff", bg = "#3e7943", gui = "bold" },
    },
    visual = {
      a = { fg = "#ffffff", bg = "#a440bc", gui = "bold" },
    },
    replace = {
      a = { fg = "#ffffff", bg = "#b74b3b", gui = "bold" },
    },
    command = {
      a = { fg = "#ffffff", bg = "#816a26", gui = "bold" },
    },
    terminal = {
      a = { fg = "#ffffff", bg = "#22777a", gui = "bold" },
    },
    inactive = {
      a = { fg = "#506573", bg = "#ffffff" },
      b = { fg = "#506573", bg = "#ffffff" },
      c = { fg = "#506573", bg = "#ffffff" },
    },
  },
  dark = {
    normal = {
      a = { fg = "#212734", bg = "#67b5ed", gui = "bold" },
      b = { fg = "#e6e6e6", bg = "#414650" },
      c = { fg = "#93969b", bg = "#212734" },
    },
    insert = {
      a = { fg = "#212734", bg = "#79be7e", gui = "bold" },
    },
    visual = {
      a = { fg = "#212734", bg = "#d58fe6", gui = "bold" },
    },
    replace = {
      a = { fg = "#212734", bg = "#e79285", gui = "bold" },
    },
    command = {
      a = { fg = "#212734", bg = "#e5c872", gui = "bold" },
    },
    terminal = {
      a = { fg = "#212734", bg = "#84dde0", gui = "bold" },
    },
    inactive = {
      a = { fg = "#93969b", bg = "#212734" },
      b = { fg = "#93969b", bg = "#212734" },
      c = { fg = "#93969b", bg = "#212734" },
    },
  },
}

return themes[vim.o.background == "light" and "light" or "dark"]
